name: demo
on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: check docker version
        run: echo "Docker version is:" && docker --version
      
      - name: check adb version
        run: echo "ADB version is:" && adb --version
