name: demo
on:
  push:
    branches: [main]

jobs:
  docker-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: pulling an image
        run: docker pull hello-world
      - name: running a container
        run: docker run hello-world
  
