name : print hello world and current date
on : 
  push : 
    branches : ["main"]

jobs : 
  print-hello-world:
    runs-on : ubuntu-latest
    steps : 
      - name : executing script and date
        run : |
          echo "Hello, World!"
          date
          
        
        
    